# Generated by Django 5.0 on 2024-01-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session_key',
        ),
    ]
