# Generated by Django 5.0 on 2024-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description field'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category Title'),
        ),
    ]
