# Generated by Django 5.0 on 2024-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expense_description_alter_expensecategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Client limit'),
        ),
    ]
