# Generated by Django 5.0 on 2024-01-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_telegram_id_profile_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
    ]
